name: example
description: A example of pubspec_builder.
version: 1.0.0

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  pubspec_parse: ^1.2.0

dev_dependencies:
  pubspec_builder:
    path: ..
  build_runner: ^2.1.11
